-- Active: 1717141082295@@192.168.1.27@3306@moremei-ai-saas-tenant-01
CREATE TABLE article_liked(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    article_id BIGINT UNSIGNED NOT NULL COMMENT '文章id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户id',
    liked TINYINT NOT NULL DEFAULT 1 COMMENT '是否点赞',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY unique_user_article (user_id, article_id)
) COMMENT '文章点赞记录';