-- Active: 1717141082295@@192.168.1.27@3306@moremei-ai-saas-tenant-01
CREATE TABLE article_view_record(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    article_id BIGINT UNSIGNED NOT NULL COMMENT '文章id',
    user_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
    view_ip VARCHAR(128) COMMENT '观众ip地址',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '文章点赞记录';