-- Active: 1717141082295@@192.168.1.29@3306@moremei-ai-saas-tenant-01
CREATE TABLE daily_tip(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    user_id BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
    content TEXT NOT NULL COMMENT 'tip内容',
    question TEXT NOT NULL COMMENT '问题',
    options JSON NOT NULL COMMENT '问题选项',
    answer VARCHAR(256) NOT NULL COMMENT '答案',
    is_public TINYINT NOT NULL DEFAULT 0 COMMENT '是否公开',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '每日小知识';
