-- Active: 1717141082295@@192.168.1.29@3306@moremei-ai-saas-tenant-01
CREATE TABLE daily_tip_record(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    user_id BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
    tip_id BIGINT(20) UNSIGNED NOT NULL COMMENT '小知识ID',
    answer VARCHAR(256) NOT NULL COMMENT '用户答案',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '每日小知识答题记录';