CREATE TABLE `mei_user_angel`(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
    `angel_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '酶好天使ID',
    `from` VARCHAR(32) NOT NULL COMMENT '添加方式',
    `user_remark` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '用户备注',
    `angel_remark` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '酶好天使备注',
    `remark` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY `user_id_key` (`user_id`)
) COMMENT '用户与酶好天使关系表';