CREATE TABLE `mei_health_user_risks`(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    `special_type` VARCHAR(64) NOT NULL COMMENT '专题类型',
    `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
    `risk_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '风险条件ID',
    `keywords` JSON NOT NULL COMMENT '关键词',
    `risk` TEXT NOT NULL COMMENT '风险条件描述',
    `reject_words` TEXT NOT NULL COMMENT '拒绝的话术',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '用户的风险条件记录';