
CREATE TABLE `svc_advisor` (
    `id` BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
    `svc_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '服务ID',
    `deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否删除',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY `idx_svc_id` (`svc_id`)
) COMMENT '服务顾问表';

CREATE TABLE `svc_advisor_user_relations` (
    `id` BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    `svc_id` VARCHAR(64) NOT NULL COMMENT '服务顾问ID',
    `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
    `from` VARCHAR(32) NOT NULL COMMENT '添加方式',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY `idx_user_id` (`user_id`)
) COMMENT '服务顾问用户关系表';