CREATE TABLE IF NOT EXISTS user_archive_infer_rules (
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    archive_template_id BIGINT(20) UNSIGNED NOT NULL COMMENT '健康档案模板ID',
    content_type VARCHAR(128) NOT NULL COMMENT '推理内容类型',
    content_id BIGINT(20) UNSIGNED NOT NULL COMMENT '推理内容ID',
    rules TEXT NOT NULL COMMENT '推理规则',
    deleted TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否删除',
    deleted_at DATETIME COMMENT '删除时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '用户健康档案推理规则';