-- Active: 1717141082295@@192.168.1.27@3306@moremei-ai-saas-tenant-01
CREATE TABLE user_uri(
    `id` BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
    `type` VARCHAR(32) NOT NULL COMMENT '资源类型',
    `key` VARCHAR(64) NOT NULL COMMENT '资源键',
    `uri` TEXT NOT NULL COMMENT '资源地址',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY `key` (`key`, `user_id`)
) COMMENT '用户资源';