-- Active: 1717141082295@@192.168.1.27@3306@moremei-ai-saas-tenant-01
CREATE TABLE user_mission_record(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户id',
    mission_id BIGINT UNSIGNED NOT NULL COMMENT '任务id',
    mission_title VARCHAR(128) NOT NULL COMMENT '任务名',
    points INT NOT NULL COMMENT '本次积分',
    detail VARCHAR(1024) COMMENT '细节内容',
    mission_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '任务完成时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '任务列表';