-- Active: 1717141082295@@192.168.1.27@3306@moremei-ai-saas-tenant-01
CREATE TABLE user_points_record(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    user_id BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
    `change` INT NOT NULL COMMENT '积分变动值',
    user_points INT NOT NULL COMMENT '变动前积分',
    type VARCHAR(64) COMMENT '记录方式',
    detail VARCHAR(256) COMMENT '积分详情',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '用户积分记录';