CREATE TABLE `user_role`(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    `uuid` VARCHAR(64) NOT NULL COMMENT '用户UUID',
    `role` VARCHAR(64) NOT NULL COMMENT '角色标识',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY `user_role_key` (`uuid`, `role`)
) COMMENT '用户角色表';
