-- Active: 1717141082295@@192.168.1.27@3306@moremei-ai-saas-tenant-01
CREATE TABLE user_points(
    id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    user_id BIGINT(20) UNSIGNED NOT NULL COMMENT '用户ID',
    points INT NOT NULL COMMENT '当前积分',
    total_points INT NOT NULL COMMENT '总积分',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '用户积分';

CREATE UNIQUE INDEX idx_user_id ON user_points(user_id);