// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	aiMessageFieldNames          = builder.RawFieldNames(&AiMessage{})
	aiMessageRows                = strings.Join(aiMessageFieldNames, ",")
	aiMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(aiMessageFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	aiMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(aiMessageFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	aiMessageModel interface {
		Insert(ctx context.Context, data *AiMessage, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*AiMessage, error)
		Update(ctx context.Context, data *AiMessage, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultAiMessageModel struct {
		conn  *gorm.DB
		table string
	}

	AiMessage struct {
		Id        uint64         `gorm:"primaryKey,column:id"`
		Day       int64          `gorm:"column:day"`        // 未回复天数
		Minute    int64          `gorm:"column:minute"`     // 间隔分钟
		Status    int64          `gorm:"column:status"`     // 0与测肤无关1做过测肤2未做过测肤3数据检查
		Type      string         `gorm:"column:type"`       // 消息类型
		Delay     int64          `gorm:"column:delay"`      // 延迟时间-小时
		Content   sql.NullString `gorm:"column:content"`    // 主题内容
		CreatedAt time.Time      `gorm:"column:created_at"` // 创建时间
		UpdatedAt time.Time      `gorm:"column:updated_at"` // 更新时间
	}
)

func (AiMessage) TableName() string {
	return "`ai_message`"
}

func newAiMessageModel(conn *gorm.DB) *defaultAiMessageModel {
	return &defaultAiMessageModel{
		conn:  conn,
		table: "`ai_message`",
	}
}

func (m *defaultAiMessageModel) Insert(ctx context.Context, data *AiMessage, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultAiMessageModel) FindOne(ctx context.Context, id uint64) (*AiMessage, error) {
	var resp AiMessage
	err := m.conn.WithContext(ctx).Model(&AiMessage{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAiMessageModel) Update(ctx context.Context, data *AiMessage, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultAiMessageModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&AiMessage{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&AiMessage{}, id).Error
	}

	return err
}

func (m *defaultAiMessageModel) tableName() string {
	return m.table
}
