// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	aiRobotWhitelistFieldNames          = builder.RawFieldNames(&AiRobotWhitelist{})
	aiRobotWhitelistRows                = strings.Join(aiRobotWhitelistFieldNames, ",")
	aiRobotWhitelistRowsExpectAutoSet   = strings.Join(stringx.Remove(aiRobotWhitelistFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	aiRobotWhitelistRowsWithPlaceHolder = strings.Join(stringx.Remove(aiRobotWhitelistFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	aiRobotWhitelistModel interface {
		Insert(ctx context.Context, data *AiRobotWhitelist, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*AiRobotWhitelist, error)
		FindOneByAiRobotIdUserId(ctx context.Context, aiRobotId uint64, userId uint64) (*AiRobotWhitelist, error)
		Update(ctx context.Context, data *AiRobotWhitelist, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultAiRobotWhitelistModel struct {
		conn  *gorm.DB
		table string
	}

	AiRobotWhitelist struct {
		Id        uint64    `gorm:"primaryKey,column:id"` // 主键
		AiRobotId uint64    `gorm:"column:ai_robot_id"`   // AI
		UserId    uint64    `gorm:"column:user_id"`       // 白名单用户
		CreatedAt time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (AiRobotWhitelist) TableName() string {
	return "`ai_robot_whitelist`"
}

func newAiRobotWhitelistModel(conn *gorm.DB) *defaultAiRobotWhitelistModel {
	return &defaultAiRobotWhitelistModel{
		conn:  conn,
		table: "`ai_robot_whitelist`",
	}
}

func (m *defaultAiRobotWhitelistModel) Insert(ctx context.Context, data *AiRobotWhitelist, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultAiRobotWhitelistModel) FindOne(ctx context.Context, id uint64) (*AiRobotWhitelist, error) {
	var resp AiRobotWhitelist
	err := m.conn.WithContext(ctx).Model(&AiRobotWhitelist{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAiRobotWhitelistModel) FindOneByAiRobotIdUserId(ctx context.Context, aiRobotId uint64, userId uint64) (*AiRobotWhitelist, error) {
	var resp AiRobotWhitelist
	err := m.conn.WithContext(ctx).Model(&AiRobotWhitelist{}).Where("`ai_robot_id` = ? and `user_id` = ?", aiRobotId, userId).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAiRobotWhitelistModel) Update(ctx context.Context, data *AiRobotWhitelist, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultAiRobotWhitelistModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&AiRobotWhitelist{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&AiRobotWhitelist{}, id).Error
	}

	return err
}

func (m *defaultAiRobotWhitelistModel) tableName() string {
	return m.table
}
