// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	aiRobotFieldNames          = builder.RawFieldNames(&AiRobot{})
	aiRobotRows                = strings.Join(aiRobotFieldNames, ",")
	aiRobotRowsExpectAutoSet   = strings.Join(stringx.Remove(aiRobotFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	aiRobotRowsWithPlaceHolder = strings.Join(stringx.Remove(aiRobotFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	aiRobotModel interface {
		Insert(ctx context.Context, data *AiRobot, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*AiRobot, error)
		FindOneByUuid(ctx context.Context, uuid string) (*AiRobot, error)
		Update(ctx context.Context, data *AiRobot, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultAiRobotModel struct {
		conn  *gorm.DB
		table string
	}

	AiRobot struct {
		Id           uint64    `gorm:"primaryKey,column:id"` // 主键
		Uuid         string    `gorm:"column:uuid"`          // 唯一值
		Name         string    `gorm:"column:name"`          // 名称
		Avator       string    `gorm:"column:avator"`        // 头像
		Description  string    `gorm:"column:description"`   // 描述信息
		WelcomeMsg   string    `gorm:"column:welcome_msg"`   // 欢迎语
		ServerHost   string    `gorm:"column:server_host"`   // 服务地址
		ApiKey       string    `gorm:"column:api_key"`       // API密钥
		LlmType      string    `gorm:"column:llm_type"`      // 大模型类型：openai，moremeiai
		LlmKnowledge string    `gorm:"column:llm_knowledge"` // 大模型知识库
		LlmPrompt    string    `gorm:"column:llm_prompt"`    // 大模型提示词
		Category     string    `gorm:"column:category"`      // 分类：assistant-助手，professor-专家教授，tool-工具
		IsTripartite uint64    `gorm:"column:is_tripartite"` // 是否第三方：0-否，1-是
		IsDefault    uint64    `gorm:"column:is_default"`    // 是否默认
		Status       uint64    `gorm:"column:status"`        // 状态：0-禁用，1-启用
		IsPublic     uint64    `gorm:"column:is_public"`     // 公开状态：0-非公开的（白名单的），1-公开的
		Sequence     int64     `gorm:"column:sequence"`      // 排序
		CreatedAt    time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt    time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (AiRobot) TableName() string {
	return "`ai_robot`"
}

func newAiRobotModel(conn *gorm.DB) *defaultAiRobotModel {
	return &defaultAiRobotModel{
		conn:  conn,
		table: "`ai_robot`",
	}
}

func (m *defaultAiRobotModel) Insert(ctx context.Context, data *AiRobot, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultAiRobotModel) FindOne(ctx context.Context, id uint64) (*AiRobot, error) {
	var resp AiRobot
	err := m.conn.WithContext(ctx).Model(&AiRobot{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAiRobotModel) FindOneByUuid(ctx context.Context, uuid string) (*AiRobot, error) {
	var resp AiRobot
	err := m.conn.WithContext(ctx).Model(&AiRobot{}).Where("`uuid` = ?", uuid).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAiRobotModel) Update(ctx context.Context, data *AiRobot, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultAiRobotModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&AiRobot{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&AiRobot{}, id).Error
	}

	return err
}

func (m *defaultAiRobotModel) tableName() string {
	return m.table
}
