// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	appUserProfileFieldNames          = builder.RawFieldNames(&AppUserProfile{})
	appUserProfileRows                = strings.Join(appUserProfileFieldNames, ",")
	appUserProfileRowsExpectAutoSet   = strings.Join(stringx.Remove(appUserProfileFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	appUserProfileRowsWithPlaceHolder = strings.Join(stringx.Remove(appUserProfileFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	appUserProfileModel interface {
		Insert(ctx context.Context, data *AppUserProfile, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*AppUserProfile, error)
		FindOneByAppUuidKey(ctx context.Context, app string, uuid string, key string) (*AppUserProfile, error)
		Update(ctx context.Context, data *AppUserProfile, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultAppUserProfileModel struct {
		conn  *gorm.DB
		table string
	}

	AppUserProfile struct {
		Id        uint64    `gorm:"primaryKey,column:id"` // Primary Key
		App       string    `gorm:"column:app"`           // 应用
		Uuid      string    `gorm:"column:uuid"`          // 系统用户UUID
		Key       string    `gorm:"column:key"`           // 键
		Value     string    `gorm:"column:value"`         // 值，用户信息
		CreatedAt time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (AppUserProfile) TableName() string {
	return "`app_user_profile`"
}

func newAppUserProfileModel(conn *gorm.DB) *defaultAppUserProfileModel {
	return &defaultAppUserProfileModel{
		conn:  conn,
		table: "`app_user_profile`",
	}
}

func (m *defaultAppUserProfileModel) Insert(ctx context.Context, data *AppUserProfile, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultAppUserProfileModel) FindOne(ctx context.Context, id uint64) (*AppUserProfile, error) {
	var resp AppUserProfile
	err := m.conn.WithContext(ctx).Model(&AppUserProfile{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAppUserProfileModel) FindOneByAppUuidKey(ctx context.Context, app string, uuid string, key string) (*AppUserProfile, error) {
	var resp AppUserProfile
	err := m.conn.WithContext(ctx).Model(&AppUserProfile{}).Where("`app` = ? and `uuid` = ? and `key` = ?", app, uuid, key).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAppUserProfileModel) Update(ctx context.Context, data *AppUserProfile, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultAppUserProfileModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&AppUserProfile{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&AppUserProfile{}, id).Error
	}

	return err
}

func (m *defaultAppUserProfileModel) tableName() string {
	return m.table
}
