// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	authProviderConfFieldNames          = builder.RawFieldNames(&AuthProviderConf{})
	authProviderConfRows                = strings.Join(authProviderConfFieldNames, ",")
	authProviderConfRowsExpectAutoSet   = strings.Join(stringx.Remove(authProviderConfFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	authProviderConfRowsWithPlaceHolder = strings.Join(stringx.Remove(authProviderConfFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	authProviderConfModel interface {
		Insert(ctx context.Context, data *AuthProviderConf, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*AuthProviderConf, error)
		FindOneByProviderTypeApp(ctx context.Context, provider string, tp string, app string) (*AuthProviderConf, error)
		Update(ctx context.Context, data *AuthProviderConf, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultAuthProviderConfModel struct {
		conn  *gorm.DB
		table string
	}

	AuthProviderConf struct {
		Id        uint64    `gorm:"primaryKey,column:id"` // Primary Key
		Type      string    `gorm:"column:type"`          // 第三方提供商类型
		Provider  string    `gorm:"column:provider"`      // 第三方登录提供商
		App       string    `gorm:"column:app"`           // 系统内app标识
		Config    string    `gorm:"column:config"`        // 三方平台应用配置信息
		CreatedAt time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (AuthProviderConf) TableName() string {
	return "`auth_provider_conf`"
}

func newAuthProviderConfModel(conn *gorm.DB) *defaultAuthProviderConfModel {
	return &defaultAuthProviderConfModel{
		conn:  conn,
		table: "`auth_provider_conf`",
	}
}

func (m *defaultAuthProviderConfModel) Insert(ctx context.Context, data *AuthProviderConf, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultAuthProviderConfModel) FindOne(ctx context.Context, id uint64) (*AuthProviderConf, error) {
	var resp AuthProviderConf
	err := m.conn.WithContext(ctx).Model(&AuthProviderConf{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAuthProviderConfModel) FindOneByProviderTypeApp(ctx context.Context, provider string, tp string, app string) (*AuthProviderConf, error) {
	var resp AuthProviderConf
	err := m.conn.WithContext(ctx).Model(&AuthProviderConf{}).Where("`provider` = ? and `type` = ? and `app` = ?", provider, tp, app).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAuthProviderConfModel) Update(ctx context.Context, data *AuthProviderConf, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultAuthProviderConfModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&AuthProviderConf{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&AuthProviderConf{}, id).Error
	}

	return err
}

func (m *defaultAuthProviderConfModel) tableName() string {
	return m.table
}
