// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	authProviderUserFieldNames          = builder.RawFieldNames(&AuthProviderUser{})
	authProviderUserRows                = strings.Join(authProviderUserFieldNames, ",")
	authProviderUserRowsExpectAutoSet   = strings.Join(stringx.Remove(authProviderUserFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	authProviderUserRowsWithPlaceHolder = strings.Join(stringx.Remove(authProviderUserFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	authProviderUserModel interface {
		Insert(ctx context.Context, data *AuthProviderUser, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*AuthProviderUser, error)
		FindOneByProviderAppOpenid(ctx context.Context, provider string, app string, openid string) (*AuthProviderUser, error)
		FindOneByProviderAppUseridOpenidUnionid(ctx context.Context, provider string, app string, userid uint64, openid string, unionid string) (*AuthProviderUser, error)
		Update(ctx context.Context, data *AuthProviderUser, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultAuthProviderUserModel struct {
		conn  *gorm.DB
		table string
	}

	AuthProviderUser struct {
		Id        uint64    `gorm:"primaryKey,column:id"` // Primary Key
		Provider  string    `gorm:"column:provider"`      // 第三方登录提供商
		App       string    `gorm:"column:app"`           // 系统内app标识
		Userid    uint64    `gorm:"column:userid"`        // 系统用户ID
		Openid    string    `gorm:"column:openid"`        // 第三方用户ID
		Name      string    `gorm:"column:name"`          // 三方平台用户名
		Unionid   string    `gorm:"column:unionid"`       // 三方平台用户统一ID
		Email     string    `gorm:"column:email"`         // 三方平台用户邮箱
		Avatar    string    `gorm:"column:avatar"`        // 三方平台用户头像
		Phone     string    `gorm:"column:phone"`         // 三方平台用户手机号
		Extra     string    `gorm:"column:extra"`         // 三方平台用户扩展信息
		CreatedAt time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (AuthProviderUser) TableName() string {
	return "`auth_provider_user`"
}

func newAuthProviderUserModel(conn *gorm.DB) *defaultAuthProviderUserModel {
	return &defaultAuthProviderUserModel{
		conn:  conn,
		table: "`auth_provider_user`",
	}
}

func (m *defaultAuthProviderUserModel) Insert(ctx context.Context, data *AuthProviderUser, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultAuthProviderUserModel) FindOne(ctx context.Context, id uint64) (*AuthProviderUser, error) {
	var resp AuthProviderUser
	err := m.conn.WithContext(ctx).Model(&AuthProviderUser{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAuthProviderUserModel) FindOneByProviderAppOpenid(ctx context.Context, provider string, app string, openid string) (*AuthProviderUser, error) {
	var resp AuthProviderUser
	err := m.conn.WithContext(ctx).Model(&AuthProviderUser{}).Where("`provider` = ? and `app` = ? and `openid` = ?", provider, app, openid).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAuthProviderUserModel) FindOneByProviderAppUseridOpenidUnionid(ctx context.Context, provider string, app string, userid uint64, openid string, unionid string) (*AuthProviderUser, error) {
	var resp AuthProviderUser
	err := m.conn.WithContext(ctx).Model(&AuthProviderUser{}).Where("`provider` = ? and `app` = ? and `userid` = ? and `openid` = ? and `unionid` = ?", provider, app, userid, openid, unionid).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAuthProviderUserModel) Update(ctx context.Context, data *AuthProviderUser, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultAuthProviderUserModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&AuthProviderUser{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&AuthProviderUser{}, id).Error
	}

	return err
}

func (m *defaultAuthProviderUserModel) tableName() string {
	return m.table
}
