// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	conversationFieldNames          = builder.RawFieldNames(&Conversation{})
	conversationRows                = strings.Join(conversationFieldNames, ",")
	conversationRowsExpectAutoSet   = strings.Join(stringx.Remove(conversationFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	conversationRowsWithPlaceHolder = strings.Join(stringx.Remove(conversationFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	conversationModel interface {
		Insert(ctx context.Context, data *Conversation, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*Conversation, error)
		FindOneByUserIdAiRobotId(ctx context.Context, userId uint64, aiRobotId uint64) (*Conversation, error)
		FindOneByUuid(ctx context.Context, uuid string) (*Conversation, error)
		Update(ctx context.Context, data *Conversation, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultConversationModel struct {
		conn  *gorm.DB
		table string
	}

	Conversation struct {
		Id        uint64    `gorm:"primaryKey,column:id"` // 主键
		Uuid      string    `gorm:"column:uuid"`          // 唯一值
		UserId    uint64    `gorm:"column:user_id"`       // 用户ID
		AiRobotId uint64    `gorm:"column:ai_robot_id"`   // AI机器人ID
		Cid       string    `gorm:"column:cid"`           // AI会话ID
		CreatedAt time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (Conversation) TableName() string {
	return "`conversation`"
}

func newConversationModel(conn *gorm.DB) *defaultConversationModel {
	return &defaultConversationModel{
		conn:  conn,
		table: "`conversation`",
	}
}

func (m *defaultConversationModel) Insert(ctx context.Context, data *Conversation, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultConversationModel) FindOne(ctx context.Context, id uint64) (*Conversation, error) {
	var resp Conversation
	err := m.conn.WithContext(ctx).Model(&Conversation{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultConversationModel) FindOneByUserIdAiRobotId(ctx context.Context, userId uint64, aiRobotId uint64) (*Conversation, error) {
	var resp Conversation
	err := m.conn.WithContext(ctx).Model(&Conversation{}).Where("`user_id` = ? and `ai_robot_id` = ?", userId, aiRobotId).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultConversationModel) FindOneByUuid(ctx context.Context, uuid string) (*Conversation, error) {
	var resp Conversation
	err := m.conn.WithContext(ctx).Model(&Conversation{}).Where("`uuid` = ?", uuid).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultConversationModel) Update(ctx context.Context, data *Conversation, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultConversationModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&Conversation{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&Conversation{}, id).Error
	}

	return err
}

func (m *defaultConversationModel) tableName() string {
	return m.table
}
