// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	messageOpinionFieldNames          = builder.RawFieldNames(&MessageOpinion{})
	messageOpinionRows                = strings.Join(messageOpinionFieldNames, ",")
	messageOpinionRowsExpectAutoSet   = strings.Join(stringx.Remove(messageOpinionFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	messageOpinionRowsWithPlaceHolder = strings.Join(stringx.Remove(messageOpinionFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	messageOpinionModel interface {
		Insert(ctx context.Context, data *MessageOpinion, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*MessageOpinion, error)
		FindOneByMessageIdUserId(ctx context.Context, messageId uint64, userId uint64) (*MessageOpinion, error)
		Update(ctx context.Context, data *MessageOpinion, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultMessageOpinionModel struct {
		conn  *gorm.DB
		table string
	}

	MessageOpinion struct {
		Id        uint64    `gorm:"primaryKey,column:id"` // 主键
		MessageId uint64    `gorm:"column:message_id"`    // 消息ID
		UserId    uint64    `gorm:"column:user_id"`       // 用户ID
		Status    int64     `gorm:"column:status"`        // 状态：0-未点赞，1-已点赞，-1-已点彩
		CreatedAt time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (MessageOpinion) TableName() string {
	return "`message_opinion`"
}

func newMessageOpinionModel(conn *gorm.DB) *defaultMessageOpinionModel {
	return &defaultMessageOpinionModel{
		conn:  conn,
		table: "`message_opinion`",
	}
}

func (m *defaultMessageOpinionModel) Insert(ctx context.Context, data *MessageOpinion, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultMessageOpinionModel) FindOne(ctx context.Context, id uint64) (*MessageOpinion, error) {
	var resp MessageOpinion
	err := m.conn.WithContext(ctx).Model(&MessageOpinion{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultMessageOpinionModel) FindOneByMessageIdUserId(ctx context.Context, messageId uint64, userId uint64) (*MessageOpinion, error) {
	var resp MessageOpinion
	err := m.conn.WithContext(ctx).Model(&MessageOpinion{}).Where("`message_id` = ? and `user_id` = ?", messageId, userId).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultMessageOpinionModel) Update(ctx context.Context, data *MessageOpinion, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultMessageOpinionModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&MessageOpinion{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&MessageOpinion{}, id).Error
	}

	return err
}

func (m *defaultMessageOpinionModel) tableName() string {
	return m.table
}
