// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	messageFieldNames          = builder.RawFieldNames(&Message{})
	messageRows                = strings.Join(messageFieldNames, ",")
	messageRowsExpectAutoSet   = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	messageRowsWithPlaceHolder = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	messageModel interface {
		Insert(ctx context.Context, data *Message, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*Message, error)
		FindOneByUuid(ctx context.Context, uuid string) (*Message, error)
		Update(ctx context.Context, data *Message, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultMessageModel struct {
		conn  *gorm.DB
		table string
	}

	Message struct {
		Id             uint64    `gorm:"primaryKey,column:id"`   // 主键
		Uuid           string    `gorm:"column:uuid"`            // 唯一值
		ConversationId uint64    `gorm:"column:conversation_id"` // 会话ID
		ParentId       uint64    `gorm:"column:parent_id"`       // 父ID
		AuthorType     string    `gorm:"column:author_type"`     // 所属人类型
		AuthorId       uint64    `gorm:"column:author_id"`       // 所属人ID
		Source         int64     `gorm:"column:source"`          // 来源：0-web，1-wecom
		Type           int64     `gorm:"column:type"`            // 类型：0-文本，1-语音，2-图片，3-视频，4-小程序，5-链接，6-文件，7-其它
		Content        string    `gorm:"column:content"`         // 会话内容ID
		CreatedAt      time.Time `gorm:"column:created_at"`      // 创建时间
		UpdatedAt      time.Time `gorm:"column:updated_at"`      // 更新时间
	}
)

func (Message) TableName() string {
	return "`message`"
}

func newMessageModel(conn *gorm.DB) *defaultMessageModel {
	return &defaultMessageModel{
		conn:  conn,
		table: "`message`",
	}
}

func (m *defaultMessageModel) Insert(ctx context.Context, data *Message, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultMessageModel) FindOne(ctx context.Context, id uint64) (*Message, error) {
	var resp Message
	err := m.conn.WithContext(ctx).Model(&Message{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultMessageModel) FindOneByUuid(ctx context.Context, uuid string) (*Message, error) {
	var resp Message
	err := m.conn.WithContext(ctx).Model(&Message{}).Where("`uuid` = ?", uuid).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultMessageModel) Update(ctx context.Context, data *Message, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultMessageModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&Message{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&Message{}, id).Error
	}

	return err
}

func (m *defaultMessageModel) tableName() string {
	return m.table
}
