// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	miniUserFieldNames          = builder.RawFieldNames(&MiniUser{})
	miniUserRows                = strings.Join(miniUserFieldNames, ",")
	miniUserRowsExpectAutoSet   = strings.Join(stringx.Remove(miniUserFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	miniUserRowsWithPlaceHolder = strings.Join(stringx.Remove(miniUserFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	miniUserModel interface {
		Insert(ctx context.Context, data *MiniUser, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*MiniUser, error)
		FindOneByOpenid(ctx context.Context, openid string) (*MiniUser, error)
		FindOneByUserId(ctx context.Context, userId uint64) (*MiniUser, error)
		Update(ctx context.Context, data *MiniUser, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultMiniUserModel struct {
		conn  *gorm.DB
		table string
	}

	MiniUser struct {
		Id             uint64    `gorm:"primaryKey,column:id"`   // 主键
		UserId         uint64    `gorm:"column:user_id"`         // 用户id
		Openid         string    `gorm:"column:openid"`          // openid
		Unionid        string    `gorm:"column:unionid"`         // unionid
		OfficialOpenid string    `gorm:"column:official_openid"` // 公众号openid
		CreatedAt      time.Time `gorm:"column:created_at"`      // 创建时间
		UpdatedAt      time.Time `gorm:"column:updated_at"`      // 更新时间
	}
)

func (MiniUser) TableName() string {
	return "`mini_user`"
}

func newMiniUserModel(conn *gorm.DB) *defaultMiniUserModel {
	return &defaultMiniUserModel{
		conn:  conn,
		table: "`mini_user`",
	}
}

func (m *defaultMiniUserModel) Insert(ctx context.Context, data *MiniUser, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultMiniUserModel) FindOne(ctx context.Context, id uint64) (*MiniUser, error) {
	var resp MiniUser
	err := m.conn.WithContext(ctx).Model(&MiniUser{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultMiniUserModel) FindOneByOpenid(ctx context.Context, openid string) (*MiniUser, error) {
	var resp MiniUser
	err := m.conn.WithContext(ctx).Model(&MiniUser{}).Where("`openid` = ?", openid).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultMiniUserModel) FindOneByUserId(ctx context.Context, userId uint64) (*MiniUser, error) {
	var resp MiniUser
	err := m.conn.WithContext(ctx).Model(&MiniUser{}).Where("`user_id` = ?", userId).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultMiniUserModel) Update(ctx context.Context, data *MiniUser, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultMiniUserModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&MiniUser{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&MiniUser{}, id).Error
	}

	return err
}

func (m *defaultMiniUserModel) tableName() string {
	return m.table
}
