// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	paramsStorageFieldNames          = builder.RawFieldNames(&ParamsStorage{})
	paramsStorageRows                = strings.Join(paramsStorageFieldNames, ",")
	paramsStorageRowsExpectAutoSet   = strings.Join(stringx.Remove(paramsStorageFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	paramsStorageRowsWithPlaceHolder = strings.Join(stringx.Remove(paramsStorageFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	paramsStorageModel interface {
		Insert(ctx context.Context, data *ParamsStorage, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*ParamsStorage, error)
		Update(ctx context.Context, data *ParamsStorage, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultParamsStorageModel struct {
		conn  *gorm.DB
		table string
	}

	ParamsStorage struct {
		Id          uint64         `gorm:"primaryKey,column:id"` // Primary Key
		UserId      uint64         `gorm:"column:user_id"`       // 用户ID
		Params      string         `gorm:"column:params"`        // 参数内容
		Description sql.NullString `gorm:"column:description"`   // 参数描述
		ExpireAt    sql.NullTime   `gorm:"column:expire_at"`     // 过期时间
		AccessCount uint64         `gorm:"column:access_count"`  // 访问次数
		CreatedAt   time.Time      `gorm:"column:created_at"`    // 创建时间
		UpdatedAt   time.Time      `gorm:"column:updated_at"`    // 更新时间
	}
)

func (ParamsStorage) TableName() string {
	return "`params_storage`"
}

func newParamsStorageModel(conn *gorm.DB) *defaultParamsStorageModel {
	return &defaultParamsStorageModel{
		conn:  conn,
		table: "`params_storage`",
	}
}

func (m *defaultParamsStorageModel) Insert(ctx context.Context, data *ParamsStorage, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultParamsStorageModel) FindOne(ctx context.Context, id uint64) (*ParamsStorage, error) {
	var resp ParamsStorage
	err := m.conn.WithContext(ctx).Model(&ParamsStorage{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultParamsStorageModel) Update(ctx context.Context, data *ParamsStorage, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultParamsStorageModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&ParamsStorage{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&ParamsStorage{}, id).Error
	}

	return err
}

func (m *defaultParamsStorageModel) tableName() string {
	return m.table
}
