// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	sharedChatHistoryFieldNames          = builder.RawFieldNames(&SharedChatHistory{})
	sharedChatHistoryRows                = strings.Join(sharedChatHistoryFieldNames, ",")
	sharedChatHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(sharedChatHistoryFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	sharedChatHistoryRowsWithPlaceHolder = strings.Join(stringx.Remove(sharedChatHistoryFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	sharedChatHistoryModel interface {
		Insert(ctx context.Context, data *SharedChatHistory, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*SharedChatHistory, error)
		FindOneByUuid(ctx context.Context, uuid string) (*SharedChatHistory, error)
		Update(ctx context.Context, data *SharedChatHistory, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultSharedChatHistoryModel struct {
		conn  *gorm.DB
		table string
	}

	SharedChatHistory struct {
		Id        uint64    `gorm:"primaryKey,column:id"`
		Uuid      string    `gorm:"column:uuid"`       // 分享ID
		UserId    uint64    `gorm:"column:user_id"`    // 分享者ID
		UserName  string    `gorm:"column:user_name"`  // 分享者名称
		Messages  string    `gorm:"column:messages"`   // 聊天记录JSON
		CreatedAt time.Time `gorm:"column:created_at"` // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"` // 更新时间
	}
)

func (SharedChatHistory) TableName() string {
	return "`shared_chat_history`"
}

func newSharedChatHistoryModel(conn *gorm.DB) *defaultSharedChatHistoryModel {
	return &defaultSharedChatHistoryModel{
		conn:  conn,
		table: "`shared_chat_history`",
	}
}

func (m *defaultSharedChatHistoryModel) Insert(ctx context.Context, data *SharedChatHistory, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultSharedChatHistoryModel) FindOne(ctx context.Context, id uint64) (*SharedChatHistory, error) {
	var resp SharedChatHistory
	err := m.conn.WithContext(ctx).Model(&SharedChatHistory{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultSharedChatHistoryModel) FindOneByUuid(ctx context.Context, uuid string) (*SharedChatHistory, error) {
	var resp SharedChatHistory
	err := m.conn.WithContext(ctx).Model(&SharedChatHistory{}).Where("`uuid` = ?", uuid).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultSharedChatHistoryModel) Update(ctx context.Context, data *SharedChatHistory, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultSharedChatHistoryModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&SharedChatHistory{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&SharedChatHistory{}, id).Error
	}

	return err
}

func (m *defaultSharedChatHistoryModel) tableName() string {
	return m.table
}
