// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	smsFieldNames          = builder.RawFieldNames(&Sms{})
	smsRows                = strings.Join(smsFieldNames, ",")
	smsRowsExpectAutoSet   = strings.Join(stringx.Remove(smsFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	smsRowsWithPlaceHolder = strings.Join(stringx.Remove(smsFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	smsModel interface {
		Insert(ctx context.Context, data *Sms, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*Sms, error)
		Update(ctx context.Context, data *Sms, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultSmsModel struct {
		conn  *gorm.DB
		table string
	}

	Sms struct {
		Id         uint64       `gorm:"primaryKey,column:id"` // 主键
		PhoneNum   string       `gorm:"column:phone_num"`     // 号码
		BizType    string       `gorm:"column:biz_type"`      // 业务类型
		Content    string       `gorm:"column:content"`       // 内容
		Status     int64        `gorm:"column:status"`        // 状态：0-未发送，1-发送中，2-发送成功，3-发送失败
		ClientIp   string       `gorm:"column:client_ip"`     // 客户端请求 IP 地址
		RequestId  string       `gorm:"column:request_id"`    // 请求ID
		SerialNo   string       `gorm:"column:serial_no"`     // 发送流水号
		Code       string       `gorm:"column:code"`          // 错误码
		Error      string       `gorm:"column:error"`         // 错误信息
		FinishedAt sql.NullTime `gorm:"column:finished_at"`   // 完成时间
		CreatedAt  time.Time    `gorm:"column:created_at"`    // 创建时间
		UpdatedAt  time.Time    `gorm:"column:updated_at"`    // 更新时间
	}
)

func (Sms) TableName() string {
	return "`sms`"
}

func newSmsModel(conn *gorm.DB) *defaultSmsModel {
	return &defaultSmsModel{
		conn:  conn,
		table: "`sms`",
	}
}

func (m *defaultSmsModel) Insert(ctx context.Context, data *Sms, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultSmsModel) FindOne(ctx context.Context, id uint64) (*Sms, error) {
	var resp Sms
	err := m.conn.WithContext(ctx).Model(&Sms{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultSmsModel) Update(ctx context.Context, data *Sms, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultSmsModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&Sms{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&Sms{}, id).Error
	}

	return err
}

func (m *defaultSmsModel) tableName() string {
	return m.table
}
