// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	systemConfigFieldNames          = builder.RawFieldNames(&SystemConfig{})
	systemConfigRows                = strings.Join(systemConfigFieldNames, ",")
	systemConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(systemConfigFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	systemConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(systemConfigFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	systemConfigModel interface {
		Insert(ctx context.Context, data *SystemConfig, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*SystemConfig, error)
		Update(ctx context.Context, data *SystemConfig, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultSystemConfigModel struct {
		conn  *gorm.DB
		table string
	}

	SystemConfig struct {
		Id        uint64    `gorm:"primaryKey,column:id"` // 主键
		Name      string    `gorm:"column:name"`          // 名称
		Key       string    `gorm:"column:key"`           // 配置键
		Value     string    `gorm:"column:value"`         // 配置值
		ValueType string    `gorm:"column:value_type"`    // 值类型
		Group     string    `gorm:"column:group"`         // 配置组
		CreatedAt time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (SystemConfig) TableName() string {
	return "`system_config`"
}

func newSystemConfigModel(conn *gorm.DB) *defaultSystemConfigModel {
	return &defaultSystemConfigModel{
		conn:  conn,
		table: "`system_config`",
	}
}

func (m *defaultSystemConfigModel) Insert(ctx context.Context, data *SystemConfig, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultSystemConfigModel) FindOne(ctx context.Context, id uint64) (*SystemConfig, error) {
	var resp SystemConfig
	err := m.conn.WithContext(ctx).Model(&SystemConfig{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultSystemConfigModel) Update(ctx context.Context, data *SystemConfig, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultSystemConfigModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&SystemConfig{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&SystemConfig{}, id).Error
	}

	return err
}

func (m *defaultSystemConfigModel) tableName() string {
	return m.table
}
