// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	tokenRequestHistoryFieldNames          = builder.RawFieldNames(&TokenRequestHistory{})
	tokenRequestHistoryRows                = strings.Join(tokenRequestHistoryFieldNames, ",")
	tokenRequestHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(tokenRequestHistoryFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	tokenRequestHistoryRowsWithPlaceHolder = strings.Join(stringx.Remove(tokenRequestHistoryFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	tokenRequestHistoryModel interface {
		Insert(ctx context.Context, data *TokenRequestHistory, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*TokenRequestHistory, error)
		Update(ctx context.Context, data *TokenRequestHistory, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultTokenRequestHistoryModel struct {
		conn  *gorm.DB
		table string
	}

	TokenRequestHistory struct {
		Id        uint64    `gorm:"primaryKey,column:id"` // 主键
		Token     string    `gorm:"column:token"`         // token
		Route     string    `gorm:"column:route"`         // 路由
		CreatedAt time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (TokenRequestHistory) TableName() string {
	return "`token_request_history`"
}

func newTokenRequestHistoryModel(conn *gorm.DB) *defaultTokenRequestHistoryModel {
	return &defaultTokenRequestHistoryModel{
		conn:  conn,
		table: "`token_request_history`",
	}
}

func (m *defaultTokenRequestHistoryModel) Insert(ctx context.Context, data *TokenRequestHistory, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultTokenRequestHistoryModel) FindOne(ctx context.Context, id uint64) (*TokenRequestHistory, error) {
	var resp TokenRequestHistory
	err := m.conn.WithContext(ctx).Model(&TokenRequestHistory{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultTokenRequestHistoryModel) Update(ctx context.Context, data *TokenRequestHistory, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultTokenRequestHistoryModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&TokenRequestHistory{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&TokenRequestHistory{}, id).Error
	}

	return err
}

func (m *defaultTokenRequestHistoryModel) tableName() string {
	return m.table
}
