// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	tokenManageFieldNames          = builder.RawFieldNames(&TokenManage{})
	tokenManageRows                = strings.Join(tokenManageFieldNames, ",")
	tokenManageRowsExpectAutoSet   = strings.Join(stringx.Remove(tokenManageFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	tokenManageRowsWithPlaceHolder = strings.Join(stringx.Remove(tokenManageFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	tokenManageModel interface {
		Insert(ctx context.Context, data *TokenManage, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*TokenManage, error)
		FindOneByToken(ctx context.Context, token string) (*TokenManage, error)
		Update(ctx context.Context, data *TokenManage, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultTokenManageModel struct {
		conn  *gorm.DB
		table string
	}

	TokenManage struct {
		Id         uint64    `gorm:"primaryKey,column:id"` // 主键
		Token      string    `gorm:"column:token"`         // token值
		ExpireTime int64     `gorm:"column:expire_time"`   // 过期时间
		CreatedAt  time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt  time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (TokenManage) TableName() string {
	return "`token_manage`"
}

func newTokenManageModel(conn *gorm.DB) *defaultTokenManageModel {
	return &defaultTokenManageModel{
		conn:  conn,
		table: "`token_manage`",
	}
}

func (m *defaultTokenManageModel) Insert(ctx context.Context, data *TokenManage, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultTokenManageModel) FindOne(ctx context.Context, id uint64) (*TokenManage, error) {
	var resp TokenManage
	err := m.conn.WithContext(ctx).Model(&TokenManage{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultTokenManageModel) FindOneByToken(ctx context.Context, token string) (*TokenManage, error) {
	var resp TokenManage
	err := m.conn.WithContext(ctx).Model(&TokenManage{}).Where("`token` = ?", token).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultTokenManageModel) Update(ctx context.Context, data *TokenManage, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultTokenManageModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&TokenManage{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&TokenManage{}, id).Error
	}

	return err
}

func (m *defaultTokenManageModel) tableName() string {
	return m.table
}
