// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*User, error)
		FindOneByUuid(ctx context.Context, uuid string) (*User, error)
		Update(ctx context.Context, data *User, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultUserModel struct {
		conn  *gorm.DB
		table string
	}

	User struct {
		Id         uint64    `gorm:"primaryKey,column:id"` // 主键
		Uuid       string    `gorm:"column:uuid"`          // 唯一值
		Nickname   string    `gorm:"column:nickname"`      // 昵称
		Avatar     string    `gorm:"column:avatar"`        // 头像
		Gender     int64     `gorm:"column:gender"`        // 性别：0-未知，1-男性，2-女性
		Birthday   string    `gorm:"column:birthday"`      // 出生日期
		Address    string    `gorm:"column:address"`       // 收货地址
		Height     uint64    `gorm:"column:height"`        // 身高
		Status     uint64    `gorm:"column:status"`        // 状态：0-禁用，1-可用
		RegisterAt time.Time `gorm:"column:register_at"`   // 注册时间
		CreatedAt  time.Time `gorm:"column:created_at"`    // 创建时间
		UpdatedAt  time.Time `gorm:"column:updated_at"`    // 更新时间
	}
)

func (User) TableName() string {
	return "`user`"
}

func newUserModel(conn *gorm.DB) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`user`",
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id uint64) (*User, error) {
	var resp User
	err := m.conn.WithContext(ctx).Model(&User{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultUserModel) FindOneByUuid(ctx context.Context, uuid string) (*User, error) {
	var resp User
	err := m.conn.WithContext(ctx).Model(&User{}).Where("`uuid` = ?", uuid).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultUserModel) Update(ctx context.Context, data *User, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultUserModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&User{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&User{}, id).Error
	}

	return err
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
