// Code generated by goctl. DO NOT EDIT!

package tenant

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	webUserFieldNames          = builder.RawFieldNames(&WebUser{})
	webUserRows                = strings.Join(webUserFieldNames, ",")
	webUserRowsExpectAutoSet   = strings.Join(stringx.Remove(webUserFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	webUserRowsWithPlaceHolder = strings.Join(stringx.Remove(webUserFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	webUserModel interface {
		Insert(ctx context.Context, data *WebUser, tx *gorm.DB) error
		FindOne(ctx context.Context, id uint64) (*WebUser, error)
		Update(ctx context.Context, data *WebUser, tx *gorm.DB) error
		Delete(ctx context.Context, id uint64, tx *gorm.DB) error
	}

	defaultWebUserModel struct {
		conn  *gorm.DB
		table string
	}

	WebUser struct {
		Id        uint64       `gorm:"primaryKey,column:id"` // 主键
		UserId    uint64       `gorm:"column:user_id"`       // 用户ID
		Mobile    string       `gorm:"column:mobile"`        // 手机号
		Deleted   uint64       `gorm:"column:deleted"`       // 删除标记：0-未删除，1-已删除
		From      int64        `gorm:"column:from"`          // 来源：0-未知1-貌美
		CreatedAt time.Time    `gorm:"column:created_at"`    // 创建时间
		UpdatedAt time.Time    `gorm:"column:updated_at"`    // 更新时间
		DeletedAt sql.NullTime `gorm:"column:deleted_at"`    // 删除时间
	}
)

func (WebUser) TableName() string {
	return "`web_user`"
}

func newWebUserModel(conn *gorm.DB) *defaultWebUserModel {
	return &defaultWebUserModel{
		conn:  conn,
		table: "`web_user`",
	}
}

func (m *defaultWebUserModel) Insert(ctx context.Context, data *WebUser, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Create(&data).Error
	} else {
		err = m.conn.WithContext(ctx).Create(&data).Error
	}
	return err
}

func (m *defaultWebUserModel) FindOne(ctx context.Context, id uint64) (*WebUser, error) {
	var resp WebUser
	err := m.conn.WithContext(ctx).Model(&WebUser{}).Where("`id` = ?", id).Take(&resp).Error
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultWebUserModel) Update(ctx context.Context, data *WebUser, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Save(data).Error
	} else {
		err = m.conn.WithContext(ctx).Save(data).Error
	}
	return err
}

func (m *defaultWebUserModel) Delete(ctx context.Context, id uint64, tx *gorm.DB) error {
	var err error
	if tx != nil {
		err = tx.WithContext(ctx).Delete(&WebUser{}, id).Error
	} else {
		err = m.conn.WithContext(ctx).Delete(&WebUser{}, id).Error
	}

	return err
}

func (m *defaultWebUserModel) tableName() string {
	return m.table
}
