// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "moremei/ai-saas/cmd/tenant/api/internal/handler/auth"
	chat "moremei/ai-saas/cmd/tenant/api/internal/handler/chat"
	common "moremei/ai-saas/cmd/tenant/api/internal/handler/common"
	user "moremei/ai-saas/cmd/tenant/api/internal/handler/user"
	"moremei/ai-saas/cmd/tenant/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/configs", Handler: common.GetConfigsHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/config/:config_key", Handler: common.GetConfigHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/sms/sign", Handler: common.GetSmsSignHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/sms/send", Handler: common.SendSmsHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/version/:app_name", Handler: common.GetAppVersionHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/params/:param_id", Handler: common.GetParamsHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/app/link", Handler: common.GetAppLinkHandler(serverCtx)},
		},
		rest.WithPrefix("/common"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodPost, Path: "/file/put-sign", Handler: common.FilePutSignHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/params/save", Handler: common.SaveParamsHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/common"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodPost, Path: "/login", Handler: auth.LoginHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/mini", Handler: auth.MiniLoginHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/mini/register", Handler: auth.MiniRegisterHandler(serverCtx)},
		},
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenAuthMiddleware},
			[]rest.Route{{Method: http.MethodPost, Path: "/token", Handler: auth.GetTokenHandler(serverCtx)}}...,
		),
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/profile", Handler: user.GetUserProfileHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/mobile", Handler: user.BindingMobileHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/info", Handler: user.UpdateUserInfoHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/app/:app_name/profile", Handler: user.GetUserAppProfileHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/app/:app_name/profile", Handler: user.SetUserAppProfileHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/height", Handler: user.SetUserHeightHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/airobot/:rid", Handler: chat.GetAiRobotHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/conversations", Handler: chat.GetConversationsHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/conversation", Handler: chat.AddConversationHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/conversation/messages", Handler: chat.GetConversationMessagesHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/conversation/message/:message_id/opinion", Handler: chat.OpinionConversationMessageHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/conversation/message/text-to-audio", Handler: chat.TextToSpeechHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/conversation/message/:message_id/audio", Handler: chat.MessageToSpeechHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/robot/message", Handler: chat.SendRobotMessageHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/history/:id", Handler: chat.GetRobotChatHistoryHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/robot/message/sse", Handler: chat.SendRobotMessageSseHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/robot/share/:id", Handler: chat.ShareRobotChatHistoryHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/robot/share/:id", Handler: chat.GetShareRobotChatHistoryHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/robot/:robot_id/opening-statement", Handler: chat.GetRobotOpeningStatementHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/file/detect", Handler: chat.FileDetectHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/chat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenCheckMiddleware},
			[]rest.Route{{Method: http.MethodGet, Path: "/airobots", Handler: chat.GetAiRobotsHandler(serverCtx)}}...,
		),
		rest.WithPrefix("/chat"),
	)
}
